version: "3.3"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    container_name: mysqlcont
    restart: always
    env_file: .env
    volumes:
      - mysql-data:/var/lib/mysql # Persistent storage for database data
    ports:
      - 33066:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 10s
      retries: 5

  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - ${ADMINER_PORT}:8080

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    volumes:
      - ./src:/node/app/src #For hot reloading
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    container_name: node-app

volumes:
  mysql-data:
  # Define a named volume for persistent MySQL data
